# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        offer_adapter:
            awss3v3:
                client: Aws\S3\S3Client
                bucket: '%env(AWS_S3_BUCKET_NAME)%'
    filesystems:
        offer_photo_fs:
            adapter: offer_adapter
            mount: offer_photo_fs
            visibility: public
