api_auth:
    path:   /collecteur_api/auth

test:
    path:   /collecteur_api/test
    controller:	App\Controller\TestController::index

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
